repos:
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black

  - repo: local
    hooks:
      - id: pylint-check
        name: Run pylint on staged files
        entry: bash -c 'pylint $(git diff --cached --name-only --diff-filter=ACM | grep -E "\.py$" | grep -vE "^(tests/|docs/|build/|venv/)" || true)'
        language: system
        types: [python]

  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint
        stages: [commit-msg]
        exclude: ^(tests/|docs/|build/|venv/).*
